# 最基础的镜像，带cuda
FROM harbor1.suanleme.cn/vm/base/ubuntu/cuda:11.8.0-base-ubuntu20.04

# 安装基础包
RUN truncate -s 0 /etc/apt/sources.list && \
    printf "deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal main restricted universe multiverse\n\
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-updates main restricted universe multiverse\n\
deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ focal-backports main restricted universe multiverse\n" > /etc/apt/sources.list && \
    apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
        screen openssh-server supervisor curl wget jq && \
    mkdir -p /var/run/sshd /init /etc/supervisor/conf.d && \
    rm -rf /var/lib/apt/lists/* && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# 安装完整 CUDA Toolkit（含 nvcc）
RUN wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin && \
    mv cuda-ubuntu2004.pin /etc/apt/preferences.d/cuda-repository-pin-600 && \
    wget https://developer.download.nvidia.com/compute/cuda/11.8.0/local_installers/cuda-repo-ubuntu2004-11-8-local_11.8.0-520.61.05-1_amd64.deb && \
    dpkg -i cuda-repo-ubuntu2004-11-8-local_11.8.0-520.61.05-1_amd64.deb && \
    cp /var/cuda-repo-ubuntu2004-11-8-local/cuda-*-keyring.gpg /usr/share/keyrings/ && \
    apt update && \
    apt install -y cuda-toolkit-11-8 && \
    rm cuda-repo-ubuntu2004-11-8-local_11.8.0-520.61.05-1_amd64.deb && \
    rm -rf /var/lib/apt/lists/*

# 安装 code-server 并配置 SSH
RUN bash -c "source ~/.bashrc && curl -fsSL https://code-server.dev/install.sh | sh" 

# 安装常用 code-server 插件
RUN code-server --install-extension ms-python.python \
    && code-server --install-extension ms-pyright.pyright \
    && code-server --install-extension ms-toolsai.jupyter \
    && code-server --install-extension ms-python.debugpy
